apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  namespace: blog
  labels:
    app: wordpress-svc
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.135
  ports:
    - name: wordpress-svc-port
      protocol: TCP
      port: 80
      targetPort: 80
  selector: 
    app: wordpress-pod