apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: wordpress-ns
  labels:
    app: mysql-svc
spec:
  ports:
    - name: mysql-svc-port
      protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
  selector: 
    app: mysql-pod
