apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openebs-jiva-csi-pvc
  namespace: wordpress-ns
spec:
  volumeMode: Filesystem
  storageClassName: openebs-jiva-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi