apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-openebs-nfs
  namespace: blog
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-rwx