apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: wordpress-ns
  labels:
    app: mysql-pvc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
    limits:
      storage: 2Gi
  selector:
    matchLabels:
      app: mysql-pv
