apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: wordpress-ns
  labels:
    app: wordpress-pvc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
    limits:
      storage: 1Gi
  selector:
    matchLabels:
      app: wordpress-pv
