apiVersion: v1
kind: Pod
metadata:
  name: wordpress-pod
  namespace: wordpress-ns
  labels:
    app: wordpress-pod
spec:
  containers:
    - name: wordpress
      image: wordpress:latest
      ports:
        - name: wordpress-port
          containerPort: 80
      env:
        - name: WORDPRESS_DB_USER
          value: "w_user"
        - name: WORDPRESS_DB_PASSWORD
          value: "w_pass"
        - name: WORDPRESS_DB_HOST
          value: "mysql-svc:3306"
        - name: WORDPRESS_DB_NAME
          value: "wordpress"
      resources:
        requests:
          cpu: "125m"
          memory: "256Mi"
        limits:
          cpu: "250m"
          memory: "512Mi"
      startupProbe:
        tcpSocket:
          port: wordpress-port
        initialDelaySeconds: 0
        periodSeconds: 10
        failureThreshold: 40
      livenessProbe:
        tcpSocket:
          port: wordpress-port
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 2
        failureThreshold: 3
      readinessProbe:
        exec:
          command:
            - "/bin/sh"
            - "-c"
            - "curl -s http://127.0.0.1"
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 2
        failureThreshold: 3
      volumeMounts:
        - name: wordpress-data
          mountPath: /var/www/html 
  volumes:
    - name: wordpress-data
      persistentVolumeClaim:
        claimName: wordpress-pvc
