apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-csi-nfs
  namespace: wordpress-ns
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: sc-csi-nfs