apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-csi-nfs
  # 设置为默认存储类,可以不用设置
  # annotations:
  #  storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: nfs-server.nfs.svc.cluster.local
  share: /
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1