apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: blog
data:
  mysql.db: d29yZHByZXNz
  mysql.pwd: d19wYXNz
  mysql.user: d191c2Vy
  mysql.host: bXlzcWwtMC5teXNxbC5ibG9nLnN2Yy5jbHVzdGVyLmxvY2Fs